backend:
  name: git-gateway

local_backend: true

publish_mode: editorial_workflow
media_folder: public/content/media/img
public_folder: img

media_library:
  name: cloudinary
  config:
    cloud_name: "dqxchogr2"
    api_key: "282943535424637"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog"
    label: "Blog Posts"
    label_singular: "Post"
    folder: "public/content/blog"
    create: true
    path: "{{language}}/{{slug}}"
    summary: "{{title}} ({{year}}-{{month}}-{{day}})"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "fr"],
          default: "en",
        }
      - {
          label: "Publish Date",
          name: "publish_date",
          widget: "datetime",
          dateFormat: "MMMM DD, YYYY",
          format: "'YYYY-MM-DD'", #"YYYY-MM-DD",
          timeFormat: false,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
    view_filters:
      - label: "English"
        field: language
        pattern: "en"
      - label: "French"
        field: language
        pattern: "fr"

  - name: "pages"
    label: "Site Pages"
    label_singular: "Page"
    folder: "public/content/pages"
    path: "{{language}}/{{title}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "fr"],
          default: "en",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "public/content/projects"
    path: "{{language}}/{{slug}}"
    create: true
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - { label: "Year", name: "date", widget: "string", default: "2020" }
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "fr"],
          default: "en",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "execs"
    label: "Meet the Execs"
    label_singular: "Exec Bio"
    folder: "public/content/exec"
    path: "{{language}}/{{fields.name}}"
    create: true
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "fr"],
          default: "en",
        }
      - {
        label: "Picture",
        name: "picture",
        widget: "image",
        required: false,
      }
      - { label: "Body", name: "body", widget: "markdown" }
